import mongoose from "mongoose";
const fighterjetSchema=new mongoose.Schema({
  userId:{
      type:mongoose.Schema.Types.ObjectId,
      ref:"User"
    },
  jetModel:{
    type:String,
    required:true
   },
  hours:{
     type:Number,
     required:true
  },
  payload:{
     type:Number,
     required:true
  },
  altitude:{
    type:Number,
    required:true
  },
  speed:{
    type:Number,
    required:true
  },
  distance:{
    type:Number
  },
  mission:{
    type:String,
    required:true
  },
   totalCO2:{
      type:Number,
      required:true,
    },
  ecoScore:{
      type:Number,
      required:true,
  },
  label:{
      type:String,
      required:true,
    }
},
{
    timestamps:true
});

export default mongoose.model("Fighterjet",fighterjetSchema);